language: go
go:
- 1.5
sudo: false
env:
  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=arm GOARM=6
  - GIMME_OS=linux GIMME_ARCH=arm GOARM=7
install:
- go get -d -v ./...
script:
  - if [[ $GIMME_OS == "linux" && $GIMME_ARCH == "amd64" ]]; then GOARCH=$GIMME_ARCH GOOS=$GIMME_OS go test github.com/rackspace/rack/commands/... -v; fi
before_deploy:
- "./script/prep-travis-release.sh"
- cd build
deploy:
  provider: cloudfiles
  username: rackcli.drgsites
  region: IAD
  api-key:
    secure: B94hK9XBKfav8TdEPIhjwWTEKGXmcJzmZhnYDzN6YOEbfgq9ZhNfYQzHzKrcoZQUG8/mLjQUjUBxJPPlccw4UOilf7Fe0NKzI9bNxjUTwlmfGXMjOvT1CrAF/mzgr35wsGHB8N6JQwGepdhCdMC2SmywZid13DQDmm1B3c7dUNg=
  container: rackclibuilds
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  slack:
    secure: GGxapXtJ6ijPWdFdIypPwuz9nDvKbj1cmLf0edmRBDNTLbg2a1RPyFugxJbd2hEqak62m5Ue3ppY+J+boJXP2n1Eb/FOQelZd3V3lxNPpvoYgJzzq+g/TlSLakposn30PG3ySOAvtvIwGbUrbVsVS3ASBzt9s39N3HoE1CufUDA=
